calling app-adjustments.sh if exists

diff --git a/install-files/bin/wasta-initial-setup b/install-files/bin/wasta-initial-setup
--- a/install-files/bin/wasta-initial-setup
+++ b/install-files/bin/wasta-initial-setup
@@ -10,6 +10,8 @@
 #   2015-10-25 rik: re-working for Ubuntu 15.10
 #       - accounting for 'auto' input parameter: will then run
 #         non-interactively.
+#   2018-02-28 rik: calling wasta-reset with logged in user instead of root
+#       - calling app-adjustments.sh script (from wasta-multidesktop) if exists
 #
 # ==============================================================================
 
@@ -152,19 +154,22 @@ then
     exit 1
 fi
 
-# rik: app-adjustments.sh now in wasta-multidesktop so can be run on login
-# echo
-# echo "*** Calling app-adjustments.sh script"
-# echo
-# bash $DIR/scripts/app-adjustments.sh $AUTO
-# LASTERRORLEVEL=$?
-# if [ "$LASTERRORLEVEL" -ne "0" ];
-# then
-#     echo
-#     echo " *** ERROR in return from app-adjustments.sh. Exiting."
-#     echo
-#     exit 1
-# fi
+ADJUST_SCRIPT=/usr/share/wasta-multidesktop/scripts/app-adjustments.sh
+if [ -e "$ADJUST_SCRIPT" ];
+then
+    echo
+    echo "*** Calling app-adjustments.sh script"
+    echo
+    bash $ADJUST_SCRIPT $AUTO
+    LASTERRORLEVEL=$?
+    if [ "$LASTERRORLEVEL" -ne "0" ];
+    then
+        echo
+        echo " *** ERROR in return from app-adjustments.sh. Exiting."
+        echo
+        exit 1
+    fi
+fi
 
 echo
 echo "*** Calling wasta-reset to re-initialize Wasta-Linux settings"
